-- ⚠️ IMPORTANTE: Este script BORRARÁ la tabla 'expenses' antigua para crearla bien desde cero.
-- Si tenías datos reales importantes, haz un backup. Si es solo prueba, dale sin miedo.

DROP TABLE IF EXISTS expenses;

-- Crear la tabla expenses con la estructura CORRECTA (incluyendo 'type')
create table expenses (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('income', 'expense')), -- Esta es la columna que faltaba
  amount numeric not null,
  description text,
  category text, 
  user_id uuid references profiles(id),
  date timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar seguridad (RLS)
alter table expenses enable row level security;

-- Políticas de acceso (para que cada usuario vea solo lo suyo)
drop policy if exists "Users can view own expenses" on expenses;
create policy "Users can view own expenses" on expenses for select using (auth.uid() = user_id);

drop policy if exists "Users can insert own expenses" on expenses;
create policy "Users can insert own expenses" on expenses for insert with check (auth.uid() = user_id);

-- Asegurarnos que las metas también estén bien (por si acaso)
create table if not exists goals (
    id bigint generated by default as identity primary key,
    title text not null,
    target_amount numeric,
    current_amount numeric default 0,
    is_shared boolean default true,
    emoji text, 
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Seed de la meta de mudanza (solo si no existe)
insert into goals (title, target_amount, current_amount, emoji)
select 'Mudarnos Juntos 🏠', 5000000, 0, '🏠'
where not exists (select 1 from goals where title = 'Mudarnos Juntos 🏠');
