-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- PROFILES (Users)
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  username text,
  role text default 'user', -- 'user' or 'admin'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- REASONS (Por qué te amo)
create table reasons (
  id bigint generated by default as identity primary key,
  text text not null,
  category text, -- 'General', 'Funny', 'Deep'
  is_visible boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- COUPONS (Ruleta)
create table coupons (
  id bigint generated by default as identity primary key,
  text text not null,
  color text, -- CSS color or hex
  is_redeemed boolean default false,
  redeemed_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- PHOTOS (Galería)
create table photos (
  id bigint generated by default as identity primary key,
  url text not null,
  description text,
  category text, -- 'Recuerdos', 'Maravillosas', 'A tu lado'
  uploaded_by uuid references profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- EXPENSES (Gastos Personales)
create table expenses (
  id bigint generated by default as identity primary key,
  amount numeric not null,
  product text not null, -- Nombre del producto/servicio
  description text, -- Descripción opcional
  category text not null, -- 'Comida', 'Transporte', 'Entretenimiento', 'Salud', 'Hogar', 'Ropa', 'Otros'
  month integer not null, -- Mes (1-12)
  year integer not null, -- Año
  user_id uuid references profiles(id),
  date date default current_date not null, -- Fecha de la compra
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- INCOMES (Ingresos Mensuales)
create table incomes (
  id bigint generated by default as identity primary key,
  amount numeric not null,
  source text not null, -- Fuente del ingreso (Salario, Freelance, etc.)
  description text,
  month integer not null, -- Mes (1-12)
  year integer not null, -- Año
  user_id uuid references profiles(id),
  date date default current_date not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- BUDGETS (Presupuestos por categoría - opcional)
create table budgets (
  id bigint generated by default as identity primary key,
  category text not null,
  amount numeric not null, -- Límite de presupuesto
  month integer not null,
  year integer not null,
  user_id uuid references profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(category, month, year, user_id)
);

-- RLS POLICIES (Row Level Security)
alter table profiles enable row level security;
alter table reasons enable row level security;
alter table coupons enable row level security;
alter table photos enable row level security;
alter table expenses enable row level security;
alter table incomes enable row level security;
alter table budgets enable row level security;

-- Simple policies for MVP (Open read for authenticated, Write for admin/owner)
-- (Adjust strictly for production)

create policy "Public profiles are viewable by everyone." on profiles for select using ( true );
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );

create policy "Reasons are viewable by everyone" on reasons for select using ( true );
create policy "Admins can insert reasons" on reasons for insert with check ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

-- ... more policies as needed
