-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- PROFILES (Users)
create table if not exists profiles (
  id uuid references auth.users not null primary key,
  email text,
  username text,
  role text default 'user', -- 'user' or 'admin'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- REASONS (Por qué te amo)
create table if not exists reasons (
  id bigint generated by default as identity primary key,
  text text not null,
  category text, -- 'General', 'Funny', 'Deep'
  is_visible boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- COUPONS (Ruleta)
create table if not exists coupons (
  id bigint generated by default as identity primary key,
  text text not null,
  color text, -- CSS color or hex
  is_redeemed boolean default false,
  redeemed_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- PHOTOS (Galería)
create table if not exists photos (
  id bigint generated by default as identity primary key,
  url text not null,
  description text,
  category text, -- 'Recuerdos', 'Maravillosas', 'A tu lado'
  uploaded_by uuid references profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- BUCKET LIST (Cosas por hacer)
create table if not exists bucket_list (
  id bigint generated by default as identity primary key,
  title text not null,
  is_completed boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- EXPENSES (Phase 2)
-- EXPENSES & INCOME (Phase 2)
create table if not exists expenses (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('income', 'expense')), 
  amount numeric not null,
  description text,
  category text, -- Can be 'Transporte' or 'Didardo 🚗', controlled by frontend logic
  user_id uuid references profiles(id),
  date timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- SAVINGS GOALS & CONTRIBUTIONS (Phase 2)
create table if not exists goals (
    id bigint generated by default as identity primary key,
    title text not null, -- e.g. "Mudarnos", "Vacaciones"
    target_amount numeric, -- Optional target
    current_amount numeric default 0,
    is_shared boolean default true,
    emoji text, 
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists contributions (
    id bigint generated by default as identity primary key,
    goal_id bigint references goals(id),
    user_id uuid references profiles(id),
    amount numeric not null,
    note text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS POLICIES (Row Level Security)
-- Enabling RLS is safe to run multiple times
alter table profiles enable row level security;
alter table reasons enable row level security;
alter table coupons enable row level security;
alter table photos enable row level security;
alter table bucket_list enable row level security;
alter table expenses enable row level security;

-- SAFE POLICY CREATION (Drop first to avoid duplication errors)

-- PROFILES
drop policy if exists "Public profiles are viewable by everyone." on profiles;
create policy "Public profiles are viewable by everyone." on profiles for select using ( true );

drop policy if exists "Users can insert their own profile." on profiles;
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );

-- REASONS
drop policy if exists "Reasons are viewable by everyone" on reasons;
create policy "Reasons are viewable by everyone" on reasons for select using ( true );

drop policy if exists "Admins can insert reasons" on reasons;
create policy "Admins can insert reasons" on reasons for insert with check ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

-- BUCKET LIST
drop policy if exists "Bucket list is public" on bucket_list;
create policy "Bucket list is public" on bucket_list for select using ( true );

drop policy if exists "Auth users can edit bucket list" on bucket_list;
create policy "Auth users can edit bucket list" on bucket_list for all using ( auth.role() = 'authenticated' );

-- GOALS & CONTRIBUTIONS POLICIES
drop policy if exists "Goals public view" on goals;
create policy "Goals public view" on goals for select using (true);
create policy "Auth users edit goals" on goals for all using (auth.role() = 'authenticated');

drop policy if exists "Contributions public view" on contributions;
create policy "Contributions public view" on contributions for select using (true);
create policy "Auth users add contributions" on contributions for insert with check (auth.uid() = user_id);

-- SEED DATA (Goals)
insert into goals (title, target_amount, current_amount, emoji)
select 'Mudarnos Juntos 🏠', 5000000, 0, '🏠'
where not exists (select 1 from goals where title = 'Mudarnos Juntos 🏠');


-- SEED DATA (Bucket List)
-- Use ON CONFLICT DO NOTHING or checks to avoid dupes, but for simplicity in this MVP script, 
-- we will just insert. If you run this multiple times, you might get duplicate list items.
-- To fix: clear the table first or just ignore for now.
-- Ideally:
insert into bucket_list (title)
select title from (values 
  ('Pizza epica en la costa'),
  ('Ir a pasear a un pueblardo'),
  ('Vacaciones'),
  ('trekking con la fokin gorda'),
  ('ir a casa chinchin'),
  ('Cocinar algo'),
  ('BINGO'),
  ('barrio chino v2'),
  ('museo de arte decorativo'),
  ('diseñar depto'),
  ('candy moon')
) as v(title)
where not exists (select 1 from bucket_list where title = v.title);
