-- =============================================
-- LISTA DEL DÍA A DÍA (mandados, supermercado, trámites)
-- Distinta de home_shopping_list, que es para compras grandes de mudanza.
-- =============================================

CREATE TABLE IF NOT EXISTS home_daily_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT DEFAULT 'Otros', -- Supermercado, Farmacia, Trámites, Otros
  assigned_to TEXT, -- 'Martina' | 'Ramiro' | 'Los dos'
  is_completed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE home_daily_tasks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "home_daily_tasks_select" ON home_daily_tasks;
CREATE POLICY "home_daily_tasks_select" ON home_daily_tasks FOR SELECT USING (true);
DROP POLICY IF EXISTS "home_daily_tasks_all" ON home_daily_tasks;
CREATE POLICY "home_daily_tasks_all" ON home_daily_tasks FOR ALL USING (auth.role() = 'authenticated');
