-- Anniversary Date Night Picks
-- Stores the final selections from the bracket tournament

create table if not exists anniversary_picks (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('bar', 'restaurant')),
  winner_name text not null,
  winner_instagram text,
  bracket_path jsonb, -- Full bracket history: [{round: 1, matchup: ['A', 'B'], winner: 'A'}, ...]
  picked_by uuid references profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table anniversary_picks enable row level security;

-- Anyone authenticated can view picks
drop policy if exists "Anniversary picks are viewable by authenticated users" on anniversary_picks;
create policy "Anniversary picks are viewable by authenticated users"
  on anniversary_picks for select
  using (auth.role() = 'authenticated');

-- Authenticated users can insert picks
drop policy if exists "Authenticated users can insert anniversary picks" on anniversary_picks;
create policy "Authenticated users can insert anniversary picks"
  on anniversary_picks for insert
  with check (auth.role() = 'authenticated');

-- Authenticated users can delete picks
drop policy if exists "Authenticated users can delete anniversary picks" on anniversary_picks;
create policy "Authenticated users can delete anniversary picks"
  on anniversary_picks for delete
  using (auth.role() = 'authenticated');
