-- ================================================
-- CAREER TRACKER - Abogacía UBA (Plan 2004/2008)
-- ================================================

-- Estado de cada materia por usuario
create table if not exists career_subject_status (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) default auth.uid(),
  subject_code text not null,
  status text default 'pendiente' check (status in ('pendiente', 'cursando', 'aprobada')),
  notes text,
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, subject_code)
);

-- Notas/evaluaciones individuales por materia
create table if not exists career_grades (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) default auth.uid(),
  subject_code text not null,
  eval_name text not null,
  grade numeric check (grade >= 0 and grade <= 10),
  eval_date date,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Horarios semanales de cursada
create table if not exists career_schedule (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) default auth.uid(),
  subject_code text not null,
  subject_name text not null,
  day_of_week text not null check (day_of_week in ('Lunes','Martes','Miércoles','Jueves','Viernes','Sábado')),
  start_time time not null,
  end_time time not null,
  color text not null default '#f43f5e',
  room text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS
alter table career_subject_status enable row level security;
alter table career_grades enable row level security;
alter table career_schedule enable row level security;

-- career_subject_status policies
create policy "career_status_select" on career_subject_status
  for select using (auth.role() = 'authenticated');
create policy "career_status_insert" on career_subject_status
  for insert with check (auth.role() = 'authenticated');
create policy "career_status_update" on career_subject_status
  for update using (auth.role() = 'authenticated');
create policy "career_status_delete" on career_subject_status
  for delete using (auth.role() = 'authenticated');

-- career_grades policies
create policy "career_grades_select" on career_grades
  for select using (auth.role() = 'authenticated');
create policy "career_grades_insert" on career_grades
  for insert with check (auth.role() = 'authenticated');
create policy "career_grades_update" on career_grades
  for update using (auth.role() = 'authenticated');
create policy "career_grades_delete" on career_grades
  for delete using (auth.role() = 'authenticated');

-- career_schedule policies
create policy "career_schedule_select" on career_schedule
  for select using (auth.role() = 'authenticated');
create policy "career_schedule_insert" on career_schedule
  for insert with check (auth.role() = 'authenticated');
create policy "career_schedule_update" on career_schedule
  for update using (auth.role() = 'authenticated');
create policy "career_schedule_delete" on career_schedule
  for delete using (auth.role() = 'authenticated');
