-- 📖 MEMORY BOOK SETUP
-- Tabla para guardar los recuerdos dinámicos (Nuestra Historia)

-- 1. Crear tabla 'memories'
create table if not exists memories (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) not null,
  photo_url text not null,
  description text,
  memory_date date default CURRENT_DATE,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Habilitar seguridad (RLS)
alter table memories enable row level security;

-- 3. Políticas de privacidad (Compartido: Ambos ven todo, pero solo editas lo tuyo)
-- VER: Todo el mundo (autenticado) puede ver las fotos del álbum.
create policy "Shared memories view" on memories
  for select using (auth.role() = 'authenticated');

-- INSERTAR: Cualquier usuario autenticado puede subir un recuerdo.
create policy "Shared memories insert" on memories
  for insert with check (auth.role() = 'authenticated');

-- EDITAR/BORRAR: Solo el dueño del recuerdo puede modificarlo/borrarlo.
create policy "Owner memories manage" on memories
  for all using (auth.uid() = user_id);

-- 4. Configuración de STORAGE (Si no existe el bucket, insertarlo)
-- Nota: Esto a veces requiere permisos de admin, si falla, el usuario deberá crear el bucket 'memories' manual.
insert into storage.buckets (id, name, public)
values ('memories', 'memories', true)
on conflict (id) do nothing;

-- Políticas de Storage para el bucket 'memories'
create policy "Give me access to own folder 1oj01k_0" on storage.objects
  for select using (bucket_id = 'memories');

create policy "Give me access to own folder 1oj01k_1" on storage.objects
  for insert with check (bucket_id = 'memories' and auth.role() = 'authenticated');
  
create policy "Give me access to own folder 1oj01k_2" on storage.objects
  for delete using (bucket_id = 'memories' and auth.uid() = owner);
