-- =============================================
-- NOTIFICACIONES PUSH
-- =============================================

-- 1. Suscripciones push (una fila por dispositivo/navegador suscripto)
CREATE TABLE IF NOT EXISTS push_subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) NOT NULL,
  endpoint TEXT NOT NULL UNIQUE,
  p256dh TEXT NOT NULL,
  auth TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users manage own push subscription" ON push_subscriptions;
CREATE POLICY "Users manage own push subscription" ON push_subscriptions
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- 2. Log de notificaciones ya enviadas (evita mandar la misma alerta dos veces)
-- Sin policies públicas: solo la Edge Function (con la service role key) la toca.
CREATE TABLE IF NOT EXISTS notification_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_key TEXT NOT NULL UNIQUE, -- ej: 'exam:123', 'bill:4:2026-08', 'event:9:2026-08-20'
  sent_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE notification_log ENABLE ROW LEVEL SECURITY;
