-- 📅 CALENDAR SETUP
-- Tabla para guardar fechas importantes

-- 1. Crear tabla 'events'
create table if not exists events (
  id bigint generated by default as identity primary key,
  title text not null,
  event_date date not null,
  recurrence text default 'none' check (recurrence in ('none', 'monthly', 'yearly')), -- Para cumplemeses y aniversarios
  type text default 'date', -- 'date' (Cita), 'anniversary' (Aniversario), 'trip' (Viaje), 'birthday' (Cumple), 'other'
  description text,
  created_by uuid references auth.users(id) default auth.uid(),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Habilitar seguridad (RLS)
alter table events enable row level security;

-- 3. Políticas de privacidad (Compartido: Ambos ven todo)
-- VER: Todo el mundo (autenticado) ve los eventos.
create policy "Shared events view" on events
  for select using (auth.role() = 'authenticated');

-- INSERTAR: Cualquier usuario autenticado puede agregar eventos.
create policy "Shared events insert" on events
  for insert with check (auth.role() = 'authenticated');

-- EDITAR/BORRAR: Solo el creador (o podríamos hacerlo compartido si prefieres).
-- Por ahora, dejemos que quien lo creó lo borre.
create policy "Owner events manage" on events
  for all using (auth.uid() = created_by);
