-- =============================================
-- CUENTAS FIJAS (Alquiler, Expensas, Luz, Gas, Internet...)
-- =============================================

-- 1. Bills (plantillas recurrentes)
CREATE TABLE IF NOT EXISTS home_bills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT DEFAULT 'Otros', -- Alquiler, Expensas, Servicios, Internet, Otros
  amount NUMERIC DEFAULT 0,
  due_day INTEGER NOT NULL CHECK (due_day BETWEEN 1 AND 31),
  is_active BOOLEAN DEFAULT TRUE,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Payments (un registro por cuenta pagada en un período 'YYYY-MM')
CREATE TABLE IF NOT EXISTS home_bill_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_id BIGINT REFERENCES home_bills(id) ON DELETE CASCADE,
  period TEXT NOT NULL, -- 'YYYY-MM'
  paid_by UUID REFERENCES profiles(id),
  amount_paid NUMERIC,
  paid_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(bill_id, period)
);

-- =============================================
-- RLS Policies (mismo patrón "compartido" que el resto de Nuestro Hogar)
-- =============================================
ALTER TABLE home_bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE home_bill_payments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "home_bills_select" ON home_bills;
CREATE POLICY "home_bills_select" ON home_bills FOR SELECT USING (true);
DROP POLICY IF EXISTS "home_bills_all" ON home_bills;
CREATE POLICY "home_bills_all" ON home_bills FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "home_bill_payments_select" ON home_bill_payments;
CREATE POLICY "home_bill_payments_select" ON home_bill_payments FOR SELECT USING (true);
DROP POLICY IF EXISTS "home_bill_payments_all" ON home_bill_payments;
CREATE POLICY "home_bill_payments_all" ON home_bill_payments FOR ALL USING (auth.role() = 'authenticated');
