-- =============================================
-- NUESTRO HOGAR - Complete Schema
-- =============================================

-- 1. Shopping List
CREATE TABLE IF NOT EXISTS home_shopping_list (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT DEFAULT 'Otros', -- Muebles, Electrodomésticos, Decoración, Cocina, Baño, Otros
  priority TEXT DEFAULT 'media', -- alta, media, baja
  estimated_price NUMERIC DEFAULT 0,
  is_purchased BOOLEAN DEFAULT FALSE,
  assigned_to TEXT, -- name string
  link TEXT,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Apartment Notes
CREATE TABLE IF NOT EXISTS home_apartments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT,
  rating INTEGER DEFAULT 0 CHECK (rating >= 0 AND rating <= 5),
  price NUMERIC DEFAULT 0,
  expenses NUMERIC DEFAULT 0,
  pros JSONB DEFAULT '[]'::jsonb,
  cons JSONB DEFAULT '[]'::jsonb,
  notes TEXT,
  status TEXT DEFAULT 'en_evaluacion', -- descartado, en_evaluacion, favorito
  photos JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Inspiration Board
CREATE TABLE IF NOT EXISTS home_inspiration (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  room TEXT DEFAULT 'Otros', -- Living, Cocina, Dormitorio, Baño, Balcón, Otros
  image_url TEXT,
  notes TEXT,
  source_link TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Moving Budget
CREATE TABLE IF NOT EXISTS home_moving_budget (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT DEFAULT 'Otros', -- Depósito, Comisión, Flete, Servicios, Otros
  estimated_amount NUMERIC DEFAULT 0,
  actual_amount NUMERIC DEFAULT 0,
  is_paid BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Moving Checklist
CREATE TABLE IF NOT EXISTS home_moving_checklist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  is_completed BOOLEAN DEFAULT FALSE,
  due_date DATE,
  category TEXT DEFAULT 'Otros', -- Trámites, Servicios, Mudanza, Otros
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =============================================
-- RLS Policies
-- =============================================
ALTER TABLE home_shopping_list ENABLE ROW LEVEL SECURITY;
ALTER TABLE home_apartments ENABLE ROW LEVEL SECURITY;
ALTER TABLE home_inspiration ENABLE ROW LEVEL SECURITY;
ALTER TABLE home_moving_budget ENABLE ROW LEVEL SECURITY;
ALTER TABLE home_moving_checklist ENABLE ROW LEVEL SECURITY;

-- Shopping List
DROP POLICY IF EXISTS "home_shopping_list_select" ON home_shopping_list;
CREATE POLICY "home_shopping_list_select" ON home_shopping_list FOR SELECT USING (true);
DROP POLICY IF EXISTS "home_shopping_list_all" ON home_shopping_list;
CREATE POLICY "home_shopping_list_all" ON home_shopping_list FOR ALL USING (auth.role() = 'authenticated');

-- Apartments
DROP POLICY IF EXISTS "home_apartments_select" ON home_apartments;
CREATE POLICY "home_apartments_select" ON home_apartments FOR SELECT USING (true);
DROP POLICY IF EXISTS "home_apartments_all" ON home_apartments;
CREATE POLICY "home_apartments_all" ON home_apartments FOR ALL USING (auth.role() = 'authenticated');

-- Inspiration
DROP POLICY IF EXISTS "home_inspiration_select" ON home_inspiration;
CREATE POLICY "home_inspiration_select" ON home_inspiration FOR SELECT USING (true);
DROP POLICY IF EXISTS "home_inspiration_all" ON home_inspiration;
CREATE POLICY "home_inspiration_all" ON home_inspiration FOR ALL USING (auth.role() = 'authenticated');

-- Moving Budget
DROP POLICY IF EXISTS "home_moving_budget_select" ON home_moving_budget;
CREATE POLICY "home_moving_budget_select" ON home_moving_budget FOR SELECT USING (true);
DROP POLICY IF EXISTS "home_moving_budget_all" ON home_moving_budget;
CREATE POLICY "home_moving_budget_all" ON home_moving_budget FOR ALL USING (auth.role() = 'authenticated');

-- Moving Checklist
DROP POLICY IF EXISTS "home_moving_checklist_select" ON home_moving_checklist;
CREATE POLICY "home_moving_checklist_select" ON home_moving_checklist FOR SELECT USING (true);
DROP POLICY IF EXISTS "home_moving_checklist_all" ON home_moving_checklist;
CREATE POLICY "home_moving_checklist_all" ON home_moving_checklist FOR ALL USING (auth.role() = 'authenticated');
